export const ROUTES = {
  ONBOARDING:           "/",
  LOGIN:                "/login",
  UNAUTHORIZED:         "/unauthorized",
  INTEL_V2:             "/intel/sales",
  INTEL_FULL:           "/intel",
  SALES:                "/intel/sales",
  MARGIN:               "/intel/margin",
  INVENTORY:            "/intel/inventory",
  ADS:                  "/intel/ads",
  CASH:                 "/intel/cash",
  HISTORY:              "/history",
  HISTORY_DETAIL:       "/history/detail",
  // DISCOVER:             "/discover",
  SCREENER:             "/research",
  SCREENER_ACTIONS:     "/research/actions/:id",
  CONNECT_MARKETPLACES: "/connect-marketplaces",
  ACTIONS:              "/actions",
  NEW_ANALYSIS:         "/new-analysis",
  SETTINGS:             "/settings",
  // HUBS:                 "/hubs",
  DETAILED_VIEW:        "/detailed-view/:intelType",
  PRODUCT_VIEW:         "/product-view",
  COMPARISON:           "/comparison",
  PRIVACY_POLICY:       "/privacy-policy",
  TERMS_OF_SERVICE:     "/terms-of-service",
  NOTIFICATIONS:        "/notifications",
  ACTION_LOG:           "/action-log",
  CATALOGUE:            "/catalogue",
  AGENTS:               "/agents",
  INTEGRATIONS:         "/integrations",
};
