export const ROUTES = {
  ONBOARDING:           "/",
  LOGIN:                "/login",
  UNAUTHORIZED:         "/unauthorized",
  INTEL_V2:             "/sales",
  INTEL_V2_FULL:        "/intel-v2",
  SALES:                "/sales",
  MARGIN:               "/margin",
  INVENTORY:            "/inventory",
  ADS:                  "/ads",
  CASH:                 "/cash",
  HISTORY:              "/history",
  // DISCOVER:             "/discover",
  SCREENER:             "/research",
  SCREENER_ACTIONS:     "/research/actions/:id",
  CONNECT_MARKETPLACES: "/connect-marketplaces",
  // ACTIONS:              "/actions",
  NEW_ANALYSIS:         "/new-analysis",
  SETTINGS:             "/settings",
  // HUBS:                 "/hubs",
  DETAILED_VIEW:        "/detailed-view/:intelType",
  PRODUCT_VIEW:         "/product-view",
  PRIVACY_POLICY:       "/privacy-policy",
  TERMS_OF_SERVICE:     "/terms-of-service",
  NOTIFICATIONS:        "/notifications",
  ACTION_LOG:           "/action-log",
};
